config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :contact_requests, path: "contact", only: [:new, :create] do
    collection do
      get :accepted, :introduction
    end
  end

  resources :businesses, only: [:index, :new, :create] do
    collection do
      get :home, :accepted
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "businesses#home"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/business.rb
class Business < ApplicationRecord
  COMMUNITIES = [ "Black-owned", "Female-owned", "Female-friendy", "LGBTQ+ friendly",
                  "LGBTQ+ owned", "Environmentally-friendly", "Sustainable business",
                  "Green company", "Local business", "Berlin-based", "Hamburg-based",
                  "Community-owned", "Migrant-Founder", "Migrant-Background", "Inclusive",
                  "Diverse", "Immigrant-friendly", "Internationals-friendly",
                  "Foreigners-friendly", "Asian-owned", "Arab-owned", "African-owned",
                  "Turkish-owned", "Indian-owned", "Latin-owned", "Employee-friendly",
                  "Sex-worker friendly"]

  belongs_to :business_type
  has_one_attached :avatar

  acts_as_taggable_on :languages, :tags

  before_validation :smart_add_url_protocol

  validates :name, :owner_name, :email, :business_type_id, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  validates :website, :instagram, url: { no_local: true, allow_nil: true, allow_blank: true }
  validates :telephone, :presence => true,
                        :numericality => true,
                        :length => { :minimum => 10, :maximum => 15 }

  def tags_and_language_names
    tags&.map(&:name) + languages.map(&:name)
  end

  # TODO: make this method more effective
  def self.list_records(what, where, tags, languages)
    what = BusinessType.where(name: what)
    tags = tags&.split(", ") || []
    languages = languages&.split(", ") || []

    search_result = Business.all
    search_result = search_result.where(location: where) if where.present?
    tagged_search_result = search_result.tagged_with((languages + tags), :any => true)
    search_result = tagged_search_result if tagged_search_result.present?
    search_result = search_result.where(business_type: what) if what.present?

    search_result
  end

  protected

  def smart_add_url_protocol
    unless website[/\Ahttp:\/\//] || website[/\Ahttps:\/\//]
      self.website = "https://#{website}" if website.present?
    end
    unless instagram[/\Ahttp:\/\//] || instagram[/\Ahttps:\/\//]
      self.instagram = "https://#{instagram}" if instagram.present?
    end
  end
end

app/models/business_group.rb
class BusinessGroup < ApplicationRecord
  has_many :business_types

  validates :name, presence: true
end

app/models/business_type.rb
class BusinessType < ApplicationRecord
  has_many :businesses
  belongs_to :business_group

  validates :name, :business_group, presence: true
end

app/models/contact_request.rb
class ContactRequest < ApplicationRecord
  validates :name, :email, :subject, :message, presence: true

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/models/csv_db.rb
require 'csv'

class CsvDb
  class << self
    def convert_save(model_name, csv_data)
      csv_file = csv_data.read

      CSV.parse(csv_file, headers: true) do |row|
        target_model = model_name.classify.constantize
        new_object = target_model.create(row.to_h)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/businesses_controller.rb
class BusinessesController < InheritedResources::Base

  def index
    if search_params.present?
      @businesses = Business.list_records(search_params[:what],
                                          search_params[:where],
                                          search_params[:tags],
                                          search_params[:languages])
    else
      @businesses = Business.all
    end
  end

  def home;end

  def accepted;end

  def new
    @business = Business.new
    @business_types = BusinessType.all
  end

  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to accepted_businesses_url, notice: "Business was successfully created." }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end


  private

    def business_params
      params.require(:business).permit(:name, :email, :is_owner, :owner_name, :location, :telephone, :website, :instagram, :opens_at, :closes_at, :business_type_id, :tag_list, :language_list, :avatar)
    end

    def search_params
      params.permit(:what, :where, :tags, :languages)
    end

end

app/controllers/contact_requests_controller.rb
class ContactRequestsController < ApplicationController
  def new
    @contact_request = ContactRequest.new
  end

  def create
    @contact_request = ContactRequest.new(contact_request_params)

    respond_to do |format|
      if @contact_request.save
        format.html { redirect_to accepted_contact_requests_url, notice: "Contact request was successfully created." }
        format.json { render :show, status: :created, location: @contact_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def accepted;end
  def introduction;end

  private
    def set_contact_request
      @contact_request = ContactRequest.find(params[:id])
    end

    def contact_request_params
      params.require(:contact_request).permit(:name, :email, :subject, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
  def business_invalid_class?(attribute_name)
    return "is-invalid" if @business&.errors&.messages[attribute_name].present?
  end

  def business_error_message(attribute_name)
    @business&.errors&.messages[attribute_name].join(", ")
  end
end

app/helpers/contact_requests_helper.rb
module ContactRequestsHelper
  def invalid_class?(attribute_name)
    return "is-invalid" if @contact_request&.errors&.messages[attribute_name].present?
  end

  def error_message(attribute_name)
    @contact_request&.errors&.messages[attribute_name].join(", ")
  end
end

app/views/admin/csv/upload_csv.html.erb
<%= form_for :dump, :url=> {:action=>"import_csv"}, :html => { :multipart => true } do |f| %>
  <table>
    <tr>
      <td>
        <label for="dump_file">
          Select a CSV File :
        </label>
      </td>
      <td>
        <%= f.file_field :file %>
      </td>
    </tr>
    <tr>
      <td>
        <%= submit_tag 'Submit' %>
      </td>
    </tr>
  </table>
<% end %>

app/views/businesses/_business.html.erb
<div class="call-sm-3 call-md-4 call-lg-6 py-3 py-sm-0">
  <div class="card">
    <% if Rails.env.development? && business.avatar.attached? %>
      <img src="<%= url_for(business.avatar) %>" class="card-img-top img-fluid" alt="...">
    <% else %>
      <%= image_tag("avatar_green_bg.png", :alt => "avatar", :class => "card-img-top img-fluid") %>
    <% end %>
    <div class="card-body">
      <ul class="star">
        <i class="bi bi-star-fill"></i>
        <i class="bi bi-star-fill"></i>
        <i class="bi bi-star-fill"></i>
        <i class="bi bi-star-fill"></i>
        <i class="bi bi-star-fill"></i>
        <span class="r-num">(0)</span>
      </ul>
      <h5 class="card-title">
        <%= business.name %> <br>
        <%= business.owner_name %> <br>
        <span class="card-text"><%= business.business_type&.name %> - N/A km</span>
      </h5>
      <div class="icon-1 social">
        <ul class="icon">
          <a href=<%= "tel:#{business.telephone}" %>><i class="bi bi-telephone"></i></a>
          <a href=<%= "mailto:#{business.email}" %>><i class="bi bi-envelope"></i></a>
          <a href=<%= business.website %> target="_blank"><i class="bi bi-globe"></i></a>
          <a href="#"><i class="bi bi-arrow-90deg-right"></i></a>
          <a href="#"><i class="bi bi-arrow-up-right"></i></a>
        </ul>
      </div>
      <div class="chip-b">
        <% business.tags_and_language_names&.each do |tag_name| %>
          <div class="chip c-1">
            <span class=""><%= tag_name %></span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/businesses/_home_categories.html.erb
<div class="home-categories justify-content-center">

  <div class="home-category-statement">
    Find a BOBI near you
  </div>

  <div class="home-category-list">
  </div>

</div>

app/views/businesses/_home_statement.html.erb
<!-- <h3 class="section-title">Statement</h3> -->
<div class="home-statement justify-content-center">
  <%= image_tag("statement.svg", :alt => "Statement") %>
  <p class="home-statement-txt">
    <span class="home-statement-txt-clear">Through an</span> intersectional platform,
    <span class="home-statement-txt-clear">we</span> empower local businesses
    <span class="home-statement-txt-clear">and entrepreneurs from underrepresented
    communities by</span> making them more visible <span class="home-statement-txt-clear">to
    their communities and others that would like
    to support them, thereby</span> helping to strengthen
    the economic and political power of these communities.
  </p>
</div>

app/views/businesses/_home_testimonials.html.erb
<h3 class="section-title">Testimonials</h3>
<div class="home-testimonials justify-content-center">
  <section class="carousel" aria-label="Gallery">
  
  <aside class="carousel__navigation">
    <ol class="carousel__navigation-list">
    </ol>
  </aside>

  <ol class="carousel__viewport">
  </ol>
  
  </section>
</div>

app/views/businesses/_search_form.html.erb
<%= form_tag(businesses_path, method: :get, class: "searchForm searchFull") do %>
  <div class="input-group mb-3 flex-nowrap justify-content-center">
    <%= select_tag :what,
                    option_groups_from_collection_for_select(BusinessGroup.all, :business_types, :name, :name, :name, params[:what]),
                    { class: "form-select mb-3", id: "nameBusiness", prompt: "What" } %>
    <%= text_field_tag(:where, params[:where], placeholder: "Where", class: "form-control mb-3", id: "nameBusiness") %>
    <%= text_field_tag(:tags, params[:tags], placeholder: "Attribute/Community", class: "form-control mb-3", id: "nameBusiness") %>
    <%= text_field_tag(:languages, params[:languages], placeholder: "Languages", class: "form-control mb-3", id: "typeBusinessReg") %>

    <span class="input-group-text mb-3">
      <%= button_tag(type: "submit", class: "btn btn-primary btn-small submitBtn") do %>
        <i class="bi bi-search"></i>
      <% end %>
    </span>
  </div>
<% end %>


<%= form_tag(businesses_path, method: :get, class: "searchForm searchMobile") do %>
  <div class="row">
    <div class=" mb-3">
      <%= select_tag :what,
                      option_groups_from_collection_for_select(BusinessGroup.all, :business_types, :name, :name, :name, params[:what]),
                      { class: "form-select mb-3", id: "nameBusiness", prompt: "What" } %>
    </div>
  </div>

  <div class="row">
    <div class=" mb-3">
      <%= text_field_tag(:where, params[:where], placeholder: "Where", class: "form-control mb-3", id: "nameBusiness") %>
    </div>
  </div>
  <div class="row">
    <div class=" mb-3">
      <%= text_field_tag(:tags, params[:tags], placeholder: "Attribute/Community", class: "form-control mb-3", id: "nameBusiness") %>
    </div>
  </div>

  <div class="row">
    <div class=" mb-3">
      <%= text_field_tag(:languages, params[:languages], placeholder: "Languages", class: "form-control mb-3", id: "typeBusinessReg") %>
    </div>
  </div>

  <div class="row">
    <span class="mobileSubmitBtn mb-3 btn btn-primary btn-small submitBtn">
      <%= button_tag("Search", type: "submit", class: "btn btn-primary btn-small submitBtn") %>
    </span>
  </div>
<% end %>

<style media="screen">
  .teaser .searchForm {
    position: absolute;
    margin-left: 50px;
    margin-right: 50px;
    top: 40%;
    z-index: 200;
  }


  .searchForm input {
    border-radius: 30px;
  }

  .searchForm .input-group-text {
    background-color: white;
    border-radius: 30px;
  }

  .searchForm input {
    min-width: 200px;
    max-width: 300px;
  }

  .searchForm select {
    min-width: 200px;
    max-width: 300px;
    color: gray;
    border-radius: 30px;

  }

  .searchForm button {
    border-radius: 30px;
  }

  .searchMobile button {
    width: 300px;
    min-width: 200px;
  }

  .mobileSubmitBtn {
    background-color: black;
    border-radius: 30px;
  }

  @media (max-width: 900px) {
    .searchFull {
      display: none
    }
  }

  @media (min-width: 901px) {
    .searchMobile {
      display: none
    }
  }

</style>

app/views/businesses/accepted.html.erb
<div class="main container-md mb-5">
  <div class="row justify-content-center registerHead text-justify-center">
    <div class="textRegister col-12">
      <p>Your business was sent with scucess!</p>
    </div>
    <div class="imgRegister col-12 order-first order-md-0 my-5 my-md-0">
      <%= image_tag("oh_yeah.svg", :alt => "Bobis") %>
      <!-- <img src="../assets/Bobi message.svg" style="height: 240px;"> -->
    </div>
  </div>
</div>

<style media="screen">
  .text-justify-center {
    text-align: center;
  }

  .main {
    margin-top: 50px;
  }

  body {
    height: 100vh;
  }
</style>

app/views/businesses/home.html.erb
<!-- <p style="color: green"><%= notice %></p> -->
<div class="main container-fluid mb-5 noPadding">
  <div class="teaser d-flex flex-column justify-content-center align-items-center">
    <div class="box">
            <%= image_tag("img.png", :alt => "Teaser Picture", class: "teaserPic") %>
    </div>
    <h1>Hello</h1>

    <%= render partial: 'search_form' %>

  </div>

  <%= render "home_categories" %>
  <%= render "home_statement" %>
</div>

<%= stylesheet_link_tag "home_categories" %>
<%= stylesheet_link_tag "home_statement" %>

<%= javascript_include_tag :carousel %>
<%= javascript_include_tag :categories %>

app/views/businesses/index.html.erb
<div class="main container-md mb-5">
  <div class="container">
    <%= render :partial => 'search_form' %>
  </div>

  <div class="container cnontainer-body">
    <div class="row content-row">
      <% @businesses.each do |business| %>
        <%= render business if business.present? %>
      <% end %>
    </div>
  </div>
</div>

<style>
  body {
    min-height: 100vh;
  }

  a {
    color: #D3D3D3;
  }

  .body {
    background-color:#FFDE2F;
  }

  .cnontainer-body{
    font-family: 'Inter', sans-serif;
    align-items: center;
    justify-content: center;
    background-color:#FFDE2F;
  }

  .social {
    align-items: flex-start;
  }

  .social i:hover {
    background-color:#232323;
    color:#fff;
    text-decoration:none;
  }

  .content-row>* {
    display: contents;
  }

  .main {
    margin-top: 50px;
  }

  .col-sm{
    border: 1px solid black;
    margin-top: 30px;
    border-radius: 10px;
    text-align: center;
    font-family: 'Inter', sans-serif;
    font-weight: 600;
  }
  .card{
    background-color: rgb(255, 255, 255);
    border-radius: 05%;
    margin-right: 20px;
    margin-top: 20px;
    margin-left: 20px;
  }

  .card img{
    height: 100px;
    width: 100px;
    margin: auto;
    margin-top: 20px;
    border-radius: 50px;
  }

  .star{
    color: gold;
  }
  .card-title i{
    color: yellow;
  }
  .r-num{
    color: black;
    font-weight: 400;
  }
  .card-title{
    margin-top: -10px;
    font-weight: 800;
    font-size: 16px;
    line-height: 25px;
  }

  .card-text{
    font-size: 14px;
    font-weight: 500;
  }

  .icon{
    margin-top: 15px;
  }

  .icon i{

    font-size: 14px;
    border: 1px solid rgb(197, 191, 191);
    background-color: white;
    margin: 3px;
    padding: 8px;
    border-radius: 50%;
    margin-right: 5px;
    font-weight: 900;

  }
  .icon-1{
    border: 1px solid rgb(255, 255, 255);
    height: 30px;
    align-items: flex-start;
  }
  .chip-b{
    margin-top: 30px;
    text-align: start;
  }
  .chip{
    margin-top: 10px;
    line-height: 20px;
    border-radius: 20px;
    padding-left: 20px;
    padding-right: 10px;
    padding-top: 5px;
    justify-content: space-around;
    height: 30px;
    font-size: 13px;
    display: inline-block;
    font-family: 'Inter', sans-serif;
    margin-left: 0px;
    background-color: rgb(235, 235, 235);
    font-weight: 500;
  }

  .c-1{
    margin-top: 10px;
    line-height: 20px;
    border-radius: 20px;
    padding-left: 10px;
    padding-right: 10px;
    padding-top: 5px;
    justify-content: space-around;
    height: 30px;
    font-size: 14px;
    display: inline-block;
    font-family: 'Inter', sans-serif;
    margin-left: 0px;
    background-color: rgb(235, 235, 235);
    font-weight: 500;

  }
</style>

app/views/businesses/new.html.erb
<%= render "form", business: @business %>

app/views/businesses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @business %>

<div>
  <%= link_to "Edit this business", edit_business_path(@business) %> |
  <%= link_to "Back to businesses", businesses_path %>

  <%= button_to "Destroy this business", @business, method: :delete %>
</div>

app/views/contact_requests/_contact_request.html.erb
<div id="<%= dom_id contact_request %>">
  <p>
    <strong>Name:</strong>
    <%= contact_request.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contact_request.email %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= contact_request.subject %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= contact_request.message %>
  </p>

</div>

app/views/contact_requests/accepted.html.erb
<div class="main container-md mb-5">
  <div class="row justify-content-center registerHead text-justify-center">
    <div class="textRegister col-12">
      <p>Thank you for contacting us, we will get in touch with you soon!</p>
    </div>
    <div class="imgRegister col-12 order-first order-md-0 my-5 my-md-0">
      <%= image_tag("oh_yeah.svg", :alt => "Bobis") %>
    </div>
  </div>
</div>

<style media="screen">
  .text-justify-center {
    text-align: center;
  }

  .main {
    margin-top: 50px;
  }

  body {
    height: 100vh;
  }
</style>

app/views/contact_requests/new.html.erb
<%= render "form", contact_request: @contact_request %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path("favicon.png") %>

    <title>Findbobi</title>
  </head>

  <body class="body">
    <header>
      <div class="headerContainer align-items-center container-md d-flex justify-content-between">
        <div class="logoContainer ml-1">
          <%= link_to root_path do %>
            <%= image_tag("Logo_FINDBOBI.svg", :alt => "Logo", class: "logo") %>
          <% end %>
        </div>
        <div class="navLinks d-flex">
          <div class="navLink">
            <%= link_to "Registration", new_business_path, class: "nav-link", id: "nav-link-reg" %>
          </div>
          <div class="navLink">
            <%= link_to "Contact us", new_contact_request_path, class: "nav-link", id: "nav-link-contact" %>
          </div>
        </div>
      </div>
    </header>

    <%= yield %>

    <footer>
      <div class="container-md">
        <div class="row justify-content-center ">
         <div class="col-md-3 mt-5">
         <%= image_tag("Logo_FINDBOBI.svg", :alt => "Logo", class: "logoFooter") %>
         </div>

          <div class="col-md-3 mt-5">
           <h3>Popular Searches</h3>
           <ul>
             <li><%= link_to "Dentists", businesses_path(what: "Dentists", tags: "Dentists"), class: "footer-link" %></li>
             <li><%= link_to "Restaurants", businesses_path(what: "Restaurants", tags: "Restaurants"), class: "footer-link" %></li>
             <li><%= link_to "Hairdresser", businesses_path(what: "Hairdresser", tags: "Hairdresser"), class: "footer-link" %></li>
           </ul>
          </div>
          <div class="col-md-3 mt-5">
           <h3>Popular Locations</h3>
           <ul>
             <li><%= link_to "Berlin", businesses_path(where: "Berlin", tags: "Berlin"), class: "footer-link" %></li>
             <li><%= link_to "Hamburg", businesses_path(where: "Hamburg", tags: "Hamburg"), class: "footer-link" %></li>
             <li><%= link_to "Cologne", businesses_path(where: "Cologne", tags: "Cologne"), class: "footer-link" %></li>
           </ul>
          </div>

          <div class="col-md-3 mt-5">
            <h3>About us</h3>
            <ul>
              <li><%= link_to "Who is BOBI", introduction_contact_requests_path, class: "footer-link" %></li>
              <li><%= link_to "Contact us", new_contact_request_path, class: "footer-link" %></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

<style media="screen">

body {
  background-color: #02DF8F;
  width: 100vw;
  font-size: 100%;
  font-family: "Inter", sans-serif;
  display: flex;
  flex-direction: column;
}

header {
  background-color: #ffffff;
  min-height: 80px;
  width: 100vw;
  font-weight: 500;
  color: #385aef;
  flex-grow: 0;
}

.nav-link {
  color: #212121;
}

.footer-link {
  color: #212121;
  text-decoration: none !important;
}

.headerContainer {
  height: 100%;
  padding-top: 15px;
  padding-bottom: 15px;
}
.logo {
  width: 210px;
  height: 35px;
}

header .active {
  position: relative;
}

header .active::after {
  transform: translateX(-50%);
  border-radius: 100%;
  position: absolute;
  background: #212121;
  bottom: 0px;
  height: 6px;
  content: "";
  width: 6px;
  left: 50%;
}

.registerHead {
  font-size: 2.5rem;
  color: black;
  font-weight: 700;
}

.registerHead #bobiCrew {
  width: 80%
}

.registerFormWrapper .form-control[type="text"],
.form-control[type="email"] {
  border-radius: 90px;
  padding-left: 20px;
}
.registerFormWrapper .form-control[type="textarea"] {
  border-radius: 90px;
}

.owner div:first-of-type {
  margin-left: 30px;
}

.registerFormWrapper .radioBtn {
  border-radius: 36px;
  padding-left: 15px;
  padding-right: 15px;
  margin-bottom: 10px;
}

.registerFormWrapper #startHour {
  border-top-left-radius: 90px;
  border-bottom-left-radius: 90px;
  padding-left: 20px;
}

.registerFormWrapper #closeHour {
  border-bottom-right-radius: 90px;
  border-top-right-radius: 90px;
}

.registerFormWrapper .form-control:focus {
  -webkit-box-shadow: none;
  box-shadow: none;
  border: 1px solid #212121;
}

.registerFormWrapper label {
  margin-left: 20px;
}

.registerForm {
  margin-left: 30px;
  margin-right: 50px;
}

.taggedInput {
  position: relative;
}

.taggedInput #helpBox {
  display: none;
  font-size: 0.625rem;
  padding: 10px;
  background-color: #eeeeee;
  border-radius: 20px;
}

.taggedInput input:focus ~ #helpBox {
  display: block;
}

.submitBtn {
  border-radius: 30px;
  background-color: black;
  border: none;
}

.submitBtn:hover{
  background-color: lightgray;
  color: black;

}

#fileUp {
  display: none;
}

.customFileUpload {
  cursor: pointer;
}



footer {
  width: 100%;
  color: black;
  background-color: #ffffff;
  flex-grow: 1;
}

footer h2 {
  font-size: 1.5rem;
  font-weight: 700;
}

footer h3 {
  font-size: 1rem;
  font-weight: 600;
  margin-bottom: 15px;
}

footer ul {
  list-style: none;
  margin: 0;
  padding: 0;
}

footer ul li {
  margin-bottom: 15px;
}

footer .logoFooter {
  width: 130px;
  height: 24px;
}

@media (max-width: 576px) {
  .registerHead {
    text-align: left;
    padding: 20px
  }
}


@media (min-width: 576px) {
  .main {

  }

}


@media (min-width: 573px) and (max-width: 611px) {
  .registerFormWrapper #startHour {
    border-radius: 90px;
    padding-left: 20px;
  }

  .registerFormWrapper #closeHour {
    border-radius: 90px;
    border-radius: 90px;
  }
}

@media (min-width:576px) and (max-width: 998px) {
  .registerHead #bobiCrew {
    width: 100%;
  }
}

@media (min-width: 768px) {
  .taggedInput input:focus ~ #helpBox {
    display: block;
    width: 129px;
    font-size: 0.625rem;
    padding: 10px;
    background-color: #eeeeee;
    position: absolute;
    right: 0;
    top: 15px;
    transform: translate(150px);
  }
}


@media (min-width: 1000px) {
  .textRegister {
    width: 70%;
  }
}


</style>